### ISSUE TITLE
Add build option for Raspberry Pi (armhf)

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/faas-idler#14]
This will require a Raspberry Pi or Scaleway ARMv7 (rent per hour) to test on.

Copy the approach used for the faas or faas-netes repo. This should largely be a copy/paste job.

* Update Makefile
* Create Dockerfile.armhf
* Test on a device

**Comment by rdimitrov** [comment]
Keep in mind that the image name in the docker-compose.armhf.yml file should be updated once there's a tagged build.

**Comment by rdimitrov** [comment]
Is the armhf image pushed already as the latest tag I can find is not for armhf - [openfaas/faas-idler:0.1.9](https://hub.docker.com/r/openfaas/faas-idler/tags/)?

**Comment by alexellis** [comment]
I think it's pushed as 0.1.8 because there is no CI yet.

**Comment by rdimitrov** [comment]
@alexellis: Thanks for pushing the armhf version, you can find the updated docker-compose armhf file with it here - https://github.com/openfaas-incubator/faas-idler/pull/18

**Comment by rgee0** [comment]
Derek close: Work seems to be complete.  We can re-open if I've misunderstood.
