### ISSUE TITLE
Scaling from zero on /async-function/ calls.

### ISSUE THREAD

**Issue by semchev** [openfaas-incubator/faas-idler#26]
When using the `/async-function/{func}` route, the idler does not request a scale from 0.
The gateway returns a 202 Accepted as expected, but the service does not scale.

## Expected Behaviour

Similar to the `/function/{func}` route. The function naturally takes a latency penalty, but then spins up in the background.

## Current Behaviour

When the `/async-function/<function>` route is used, if the function has been scaled to zero,
the function will not be scaled from zero. 

Note: scale_from_zero is set to "true" in the master compose file, thus it works for the synchronous calls.

## Possible Solution

Looking into the logs for the queue worker, it seems the request attempt to forward is failing, because it will attempt to POST `http://async-idle-test:8080`, and no host is found, and the 202 report returns anyway.

```
docker service logs -f func_queue_worker
...
...
func_queue-worker.1.k1322fdri864@host | Request for async-idle-test 
func_queue-worker.1.k1322fdri864@host | Post http://async-idle-test:8080/: dial tcp: lookup \
notifier on 127.0.0.11:53: no such host 
func_queue-worker.1.k1322fdri864@host | Posting report 202. 
```
No such host makes sense as it is currently scaled to 0, but this then returns a 202, and no hook is created for the faas-idler between the gateway and here, so nothing happens. To be fair, a 202 is a success code, which is misleading here, as it implies the result will be processed, when it fact it hasn't forwarded anything, which seems like a separate bug in the queue-worker.

In order to fix this, something (I'm being ambiguous here because I'm new to using the project) needs to exist between the gateway and queue worker (blocking responses similar to the synchronous requests) giving a scale request for the service prior to passing it along to the queue worker.

## Steps to Reproduce (for bugs)

1. `faas-cli new --lang dockerfile async-idle-test`
2. `faas-cli build -f async-idle-test.yml && faas-cli deploy -f async-idle-test.yml`
3. Wait for it to scale to zero.
4. `echo "some input" | faas-cli invoke -a async-idle-test`
output: `Function submitted asynchronously.`
5. `docker service ls`
output: 
```
...
...
53wtfzvhxfxe      async-idle-test      replicated          0/0       functions/async-idle-test:latest
```
6. `docker service logs -f async-idle-test`
output: No output, terminal hangs onto input pipe, which remains empty as the function has not scaled.
## Context

This affects longer-running processes or processes that are desirable to run asynchronously in general.
For these processes especially, the latency penalty for a startup is not even noticeable to the client, as it can pass an `X-Callback-Url` and continue on its way, receiving the 202 immediately, and scaling down to reduce compute is desirable for the same reasons as for synchronous requests.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? 
Docker swarm.

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04.2 LTS bionic x86_64 kernel 4.15.0-48-generic

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

OpenFaas is on the latest version from [openfaas-master](https://github.com/openfaas/faas).
(commit 5056ad0e5e24f0d5bd503388f63ad6b3151ebf86 at time of writing).

faas-idler is also on the latest version at time of writing.

**Comment by alexellis** [comment]
Thanks for your interest in OpenFaaS. I'll point you at the existing issue tracking this feature.

**Comment by alexellis** [comment]
https://github.com/openfaas/nats-queue-worker/issues/32

**Comment by alexellis** [comment]
Derek add label: duplicate
