### ISSUE TITLE
Add basic auth secrets to faas-idler

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/faas-idler#4]
Feature: faas-idler should work with the gateway when basic auth is enabled

Todo:
- [x] Add the named secrets to the YAML file for Kubernetes/Swarm
- [x] Update application code to read the secrets at the application start-up and to forward upon each API call to the API Gateway
- [x] Add validation: Crash upon loading if secrets are invalid - make an initial call to `/system/info` to validate them. This will indicate to the user that some action is required.

**Comment by alexellis** [comment]
Secrets are defined here, same for K8s and Swarm:

https://github.com/openfaas/faas/blob/master/docker-compose.yml#L36

**Comment by bartsmykla** [comment]
Tested on kubernetes cluster (EKS). Works as expected!
